MVC_Sheet2/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Sheet2.Controllers
{
    public class GradesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            try
            {
                double grade_1 = double.Parse(form["g1"]);
                double grade_2 = double.Parse(form["g2"]);
                double grade_3 = double.Parse(form["g3"]);

                double avg = (grade_1 + grade_2 + grade_3) / 3;
                String result = "";

                String grade_color = "blue";

                if (avg == 100)
                {
                    result = "A+ PERFECT!!!";
                    grade_color = "green";
                }
                else if (avg > 89 && avg < 100)
                {
                    result = "GRADE: A NUMERIC GRADE: " + avg;
                    grade_color = "green";
                }
                else if (avg > 79 && avg < 89)
                {
                    result = "GRADE: B NUMERIC GRADE: " + avg;
                    grade_color = "green";
                }
                else if (avg > 69 && avg < 79)
                {
                    result = "GRADE: C NUMERIC GRADE: " + avg;
                    grade_color = "yellow";
                }
                else if (avg > 59 && avg < 69)
                {
                    result = "GRADE: C NUMERIC GRADE: " + avg;
                    grade_color = "red";
                }
                else if (avg < 60 && avg > 0)
                {
                    result = "GRADE: F NUMERIC GRADE: " + avg;
                    grade_color = "red";
                }
                else
                {
                    result = "ERROR";
                }
                ViewData["res"] = result;
                ViewData["color"] = grade_color;
                return View();
            }
            catch (Exception e)
            {
                ViewData["res"] = "something seriously went wrong!";
                return View();
            }
        }
    }
}

MVC_Sheet2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Sheet2.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
        /*
        public ActionResult Loan()
        {
            return View();
        }

        public ActionResult Grades()
        {
            return View();
        }*/
    }
}

MVC_Sheet2/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Sheet2.Controllers
{
    public class LoanController : Controller
    {
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(String init, String intr, String yrs)
        {
            try
            {
                float result = float.Parse(init);
                float interest = float.Parse(intr);
                float years = float.Parse(yrs);

                for (int x = 0; x < years; x++)
                {
                    result += result * (interest / 100);
                }

                ViewData["res"] = "Given "+years+" years, an investment of $"+float.Parse(init)+", and an annual rate of "+interest+"%, you will have $"+ Math.Round(result, 2)+".";
                return View();
            }
            catch (Exception e)
            {
                ViewData["res"] = "Error: something really unexpected went wrong!";
                return View();
            }

        }
    }
}

MVC_Sheet2/Views/Grades/Index.cshtml
<!-- GRADES -->
@{
    ViewBag.Title = "Grades";
}

<h2>Enter your scores for the 3 tests</h2>
@using (Html.BeginForm("Index", "Grades", FormMethod.Post))
{
    @Html.Label("t1", "Test 1: ");
    @Html.TextBox("g1", "", new { type = "number", min = "0", max = "100" })
    <br/>
    <br/>
    @Html.Label("t2", "Test 2: ");
    @Html.TextBox("g2", "", new { type = "number", min = "0", max = "100" })
    <br/>
    <br/>
    @Html.Label("t3", "Test 3: ");
    @Html.TextBox("g3", "", new { type = "number", min = "0", max = "100" })
    <br/>
    <br/>
    <input type="submit" value="Calculate">
    <br/><br/>
}
@if (ViewData["res"] != null)
{
    <p style="color:@ViewData["color"];">Result: @ViewData["res"]</p>
}

MVC_Sheet2/Views/Home/index.cshtml
<!-- HOMEPAGE -->
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to Loan & Grades calculator</h2>
<br />
@Html.ActionLink("Loans", "Index", "Loan")
<br />
@Html.ActionLink("Grades", "Index", "Grades")

MVC_Sheet2/Views/Loan/Index.cshtml
<!-- LOANS -->
@{
    ViewBag.Title = "Loans";
}

<h2>Loans</h2>

<h3>Please fill out the following form</h3>
<form action="/Loan/Index" method="post">
    Enter your intial investment
    <br/>
    <input id="inital" type="number" name="init" value="@ViewData["init"]" min="0" required>
    <br/><br/>
    Enter your interest rate
    <br/>
    <input id="interest" type="number" name="intr" value="@ViewData["intr"]" min="0" required>
    <br/><br/>
    Enter the amount of years
    <br/>
    <input id="years" type="number" name="yrs" value="@ViewData["yrs"]" min="0" required>
    <br/><br/>
    <input type="submit" value="Calculate!">
    <br/><br/>
    @if (ViewData["res"] != null)
    {
        <p>@ViewData["res"]</p>
    }
</form>

MVC_Sheet2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SHEET 2", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Peter Haladay @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>